version: '3.3'
services:
  prontomed:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    network_mode: 
      host
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${DB_HOST}
      - TYPEORM_USERNAME=${DB_USER}
      - TYPEORM_PASSWORD=${DB_PASSWORD}
      - TYPEORM_DATABASE=${DB_NAME}
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=dist/**/*.entity.js