version: '3.3'
services:
  prontomed:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    network_mode: 
      host
    environment:
      - DATABASE_URL=${DATABASE_URL}