version: '3.3'
services:
  prontomed:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    network_mode: 
      host
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
