version: '3.3'
services:
  prontomed:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: 
      host
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
